### ISSUE TITLE
[1.7.9] Forge Economies/Bridge console commands

### ISSUE THREAD

**Issue by Rasgnarok** [EnvyWare/ForgeEconomies#42]
/givemoney Rasgnarok 500
[01:22:55] [Server thread/INFO] [VotingPlugin/]: Received a vote from service site 'TestVote' by player 'Rasgnarok'!
[01:22:55] [envyware_concurrency_26/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:    at java.base/java.lang.Thread.run(Thread.java:829)
>....Exception in thread "envyware_concurrency_27"
                                                  [01:22:55] [envyware_concurrency_27/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]: java.lang.NullPointerException
[01:22:55] [envyware_concurrency_27/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:    at com.envyful.economies.forge.shade.envy.api.forge.command.command.executor.CommandExecutor.execute(CommandExecutor.java:229)
[01:22:55] [envyware_concurrency_27/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:    at com.envyful.economies.forge.shade.envy.api.forge.command.command.ForgeCommand.attemptRun(ForgeCommand.java:176)
[01:22:55] [envyware_concurrency_27/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:    at com.envyful.economies.forge.shade.envy.api.forge.command.command.ForgeCommand.executeSync(ForgeCommand.java:124)
[01:22:55] [envyware_concurrency_27/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:    at com.envyful.economies.forge.shade.envy.api.forge.command.command.ForgeCommand.executeSync(ForgeCommand.java:116)
[01:22:55] [envyware_concurrency_27/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:    at com.envyful.economies.forge.shade.envy.api.forge.command.command.ForgeCommand.lambda$execute$0(ForgeCommand.java:104)
[01:22:55] [envyware_concurrency_27/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:    at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
[01:22:55] [envyware_concurrency_27/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:    at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
[01:22:55] [envyware_concurrency_27/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:1050]:    at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by Rasgnarok** [comment]
happens with eco give (admin command) too
